"""Tool endpoints for the ThirstyAI Builder CLI.

Seven routes mounted at /api/tools/{read,write,edit,shell,grep,listdir,appstore}.

Security model:
- Every route requires the standard CB_API_KEY bearer (auth.verify_bearer).
- Every route refuses to start unless THIRSTY_AI_TOOLS_ENABLED=1 is set.
  That is the opt-in. Defaults to OFF.
- The write and shell routes additionally require a confirm_token
  generated by the CLI. The token is a 6-digit code the user sees
  on their terminal and must type back. Without it, the route returns
  403. This stops a runaway agent from rm -rf'ing the user's home.
- All free-text fields have max_length. All paths are validated to
  be relative and to not contain "..". The shell command field
  rejects a hard-coded blocklist of obviously destructive patterns
  (rm -rf /, dd of=/dev/, mkfs, fork bomb, shutdown/reboot/halt).
- Every successful tool call is appended to the audit collection
  (if Mongo is up) so the user has a record of what was changed.

This is the backend half of the ThirstyAI CLI integration. The CLI
half lives at thirsty-ai-builder/cli/thirsty_ai_builder_cli/ and
talks to these routes.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import os
import re
import secrets
import subprocess
import time
from datetime import timezone
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from . import auth, ownership


router = APIRouter(prefix="/api/tools", tags=["tools"])


# ---------- opt-in gate ----------
def tools_enabled() -> bool:
    return os.environ.get("THIRSTY_AI_TOOLS_ENABLED", "").strip().lower() in {"1", "true", "yes", "on"}


# ---------- shell blocklist (defence in depth) ----------
# The confirm_token is the primary control. This is the secondary.
_SHELL_DENY_PATTERNS = [
    re.compile(r"\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|--recursive)[^\n]*?/[^\n]*$"),
    re.compile(r"\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f[a-zA-Z]*|--recursive)[^\n]*?~/?[^\n]*$"),
    re.compile(r"\bdd\s+.*\bof=/dev/"),
    re.compile(r"\bmkfs(\.[a-z0-9]+)?\b"),
    re.compile(r":\(\)\s*\{.*:\|:&.*\}\s*;:"),  # fork bomb
    re.compile(r"\bshutdown\b"),
    re.compile(r"\breboot\b"),
    re.compile(r"\bhalt\b"),
    re.compile(r"\bpoweroff\b"),
    re.compile(r"\binit\s+0\b"),
    re.compile(r">\s*/dev/sd[a-z]"),
    re.compile(r"\bchmod\s+-R\s+000\b"),
    re.compile(r"\bchown\s+-R\s+.*\s+/\b"),
]


def _shell_is_safe(command: str) -> tuple[bool, str]:
    for pat in _SHELL_DENY_PATTERNS:
        if pat.search(command):
            return False, f"command matches blocklist pattern: {pat.pattern!r}"
    return True, ""


# ---------- confirm token store (in-process) ----------
# The CLI calls POST /api/tools/confirm with the (tool, args) it
# intends to run; the server returns a 6-digit code. The CLI then
# calls the actual tool with the code in confirm_token. Codes are
# valid for 60 seconds and tied to a fingerprint so they cannot be
# replayed against a different command.
_TOKENS: dict[str, dict[str, Any]] = {}
_TOKENS_LOCK = __import__("threading").Lock()
_TOKEN_TTL_SECONDS = 60


def _purge_expired_tokens() -> None:
    now = time.time()
    with _TOKENS_LOCK:
        for k in list(_TOKENS.keys()):
            if _TOKENS[k]["expires_at"] < now:
                _TOKENS.pop(k, None)


def _fingerprint(tool: str, args: dict) -> str:
    items = sorted((k, str(v)) for k, v in args.items())
    return hashlib.sha256(f"{tool}:{items}".encode()).hexdigest()


def _issue_token(tool: str, args: dict) -> str:
    _purge_expired_tokens()
    nonce = secrets.token_hex(8)
    fp = _fingerprint(tool, args)
    digest = hashlib.sha256(f"{tool}:{fp}:{nonce}".encode()).hexdigest()
    code = str(int(digest[:6], 16) % 1000000).zfill(6)
    with _TOKENS_LOCK:
        _TOKENS[code] = {
            "tool": tool,
            "fingerprint": fp,
            "expires_at": time.time() + _TOKEN_TTL_SECONDS,
        }
    return code


def _verify_token(tool: str, args: dict, code: str) -> bool:
    _purge_expired_tokens()
    with _TOKENS_LOCK:
        entry = _TOKENS.pop(code, None)
    if entry is None:
        return False
    if entry["tool"] != tool:
        return False
    if entry["fingerprint"] != _fingerprint(tool, args):
        return False
    return True


# ---------- Pydantic models ----------
class ToolArgs(BaseModel):
    args: dict[str, Any] = Field(default_factory=dict)
    confirm_token: str | None = Field(default=None, max_length=8)


class ConfirmRequest(BaseModel):
    tool: str = Field(..., min_length=1, max_length=32)
    args: dict[str, Any] = Field(default_factory=dict)


class ConfirmResponse(BaseModel):
    code: str
    fingerprint: str
    expires_in: int


class ToolResult(BaseModel):
    ok: bool
    tool: str
    result: Any = None
    error: str | None = None
    duration_ms: int


# ---------- helpers ----------
def _require_enabled() -> None:
    if not tools_enabled():
        raise HTTPException(
            status_code=503,
            detail="THIRSTY_AI_TOOLS_ENABLED is not set. Set it to 1 in the backend's environment to enable /api/tools/*. This is the opt-in.",
        )


def _require_confirm(tool: str, args: dict, code: str | None) -> None:
    if not code:
        raise HTTPException(
            status_code=403,
            detail=f"{tool} requires a confirm_token. Call POST /api/tools/confirm first; the CLI prints the 6-digit code; the user must type it back.",
        )
    if not _verify_token(tool, args, code):
        raise HTTPException(
            status_code=403,
            detail="confirm_token is invalid, expired, or does not match the (tool, args) pair. Get a fresh one with POST /api/tools/confirm.",
        )


def _safe_relative_path(path: str) -> Path:
    if not path or len(path) > 1024:
        raise HTTPException(status_code=400, detail="path is required and must be <= 1024 chars")
    if path.startswith("/") or re.match(r"^[A-Za-z]:", path):
        raise HTTPException(status_code=400, detail="path must be relative; absolute paths are not allowed")
    if ".." in Path(path).parts:
        raise HTTPException(status_code=400, detail="path must not contain '..'")
    return Path(path)


# ---------- confirm endpoint ----------
@router.post("/confirm", response_model=ConfirmResponse, dependencies=[Depends(auth.verify_bearer)])
def confirm_endpoint(req: ConfirmRequest) -> ConfirmResponse:
    _require_enabled()
    if req.tool not in {"write", "shell"}:
        raise HTTPException(status_code=400, detail="confirm is only issued for write and shell tools")
    code = _issue_token(req.tool, req.args)
    return ConfirmResponse(
        code=code,
        fingerprint=_fingerprint(req.tool, req.args),
        expires_in=_TOKEN_TTL_SECONDS,
    )


# ---------- read ----------
class ReadArgs(BaseModel):
    path: str = Field(..., min_length=1, max_length=1024)
    max_bytes: int = Field(default=65536, ge=1, le=1048576)


@router.post("/read", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_read(req: ReadArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    p = _safe_relative_path(req.path)
    if not p.exists():
        return ToolResult(ok=False, tool="read", error=f"not found: {req.path}", duration_ms=_ms(start))
    if not p.is_file():
        return ToolResult(ok=False, tool="read", error=f"not a file: {req.path}", duration_ms=_ms(start))
    data = p.read_bytes()
    if len(data) > req.max_bytes:
        return ToolResult(
            ok=False, tool="read",
            error=f"file is {len(data)} bytes, max_bytes is {req.max_bytes}",
            duration_ms=_ms(start),
        )
    return ToolResult(ok=True, tool="read", result=data.decode("utf-8", errors="replace"), duration_ms=_ms(start))


# ---------- write ----------
class WriteArgs(BaseModel):
    path: str = Field(..., min_length=1, max_length=1024)
    content: str = Field(..., max_length=1048576)


@router.post("/write", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_write(req: ToolArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    args = req.args
    p = _safe_relative_path(args.get("path", ""))
    content = args.get("content", "")
    code = req.confirm_token
    _require_confirm("write", {"path": str(p), "content": content[:64]}, code)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return ToolResult(ok=True, tool="write", result=f"wrote {len(content)} bytes to {p}", duration_ms=_ms(start))


# ---------- edit (find-and-replace on a single file) ----------
class EditArgs(BaseModel):
    path: str = Field(..., min_length=1, max_length=1024)
    find: str = Field(..., min_length=1, max_length=65536)
    replace: str = Field(..., max_length=65536)
    expected_occurrences: int = Field(default=1, ge=0, le=10000)


@router.post("/edit", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_edit(req: EditArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    p = _safe_relative_path(req.path)
    if not p.exists() or not p.is_file():
        return ToolResult(ok=False, tool="edit", error=f"not found: {req.path}", duration_ms=_ms(start))
    text = p.read_text(encoding="utf-8")
    count = text.count(req.find)
    if count != req.expected_occurrences:
        return ToolResult(
            ok=False, tool="edit",
            error=f"found {count} occurrence(s), expected {req.expected_occurrences}. Refusing to edit.",
            duration_ms=_ms(start),
        )
    new_text = text.replace(req.find, req.replace, req.expected_occurrences)
    p.write_text(new_text, encoding="utf-8")
    return ToolResult(ok=True, tool="edit", result=f"replaced {count} occurrence(s) in {p}", duration_ms=_ms(start))


# ---------- shell ----------
class ShellArgs(BaseModel):
    command: str = Field(..., min_length=1, max_length=4096)
    cwd: str | None = Field(default=None, max_length=1024)
    timeout_seconds: int = Field(default=30, ge=1, le=300)


@router.post("/shell", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_shell(req: ToolArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    args = req.args
    command = args.get("command", "")
    cwd = args.get("cwd")
    timeout = int(args.get("timeout_seconds", 30))
    _require_confirm("shell", {"command": command, "cwd": cwd or "", "timeout_seconds": int(timeout)}, req.confirm_token)
    safe, reason = _shell_is_safe(command)
    if not safe:
        return ToolResult(ok=False, tool="shell", error=f"blocked: {reason}", duration_ms=_ms(start))
    try:
        proc = subprocess.run(
            command, shell=True, capture_output=True, text=True,
            cwd=cwd if cwd else None, timeout=timeout,
        )
        return ToolResult(
            ok=True, tool="shell",
            result={
                "stdout": proc.stdout[-8192:],
                "stderr": proc.stderr[-8192:],
                "returncode": proc.returncode,
            },
            duration_ms=_ms(start),
        )
    except subprocess.TimeoutExpired:
        return ToolResult(ok=False, tool="shell", error=f"timeout after {timeout}s", duration_ms=_ms(start))


# ---------- grep ----------
class GrepArgs(BaseModel):
    pattern: str = Field(..., min_length=1, max_length=512)
    path: str = Field(default=".", max_length=1024)
    max_matches: int = Field(default=100, ge=1, le=1000)


@router.post("/grep", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_grep(req: GrepArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    p = _safe_relative_path(req.path)
    if not p.exists():
        return ToolResult(ok=False, tool="grep", error=f"not found: {req.path}", duration_ms=_ms(start))
    rx = re.compile(req.pattern)
    matches: list[dict] = []
    files = [p] if p.is_file() else list(p.rglob("*"))
    for f in files:
        if not f.is_file() or f.stat().st_size > 1_048_576:
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for i, line in enumerate(text.splitlines(), 1):
            if rx.search(line):
                matches.append({"file": str(f), "line": i, "text": line[:512]})
                if len(matches) >= req.max_matches:
                    return ToolResult(
                        ok=True, tool="grep",
                        result={"matches": matches, "truncated": True, "count": len(matches)},
                        duration_ms=_ms(start),
                    )
    return ToolResult(ok=True, tool="grep", result={"matches": matches, "truncated": False, "count": len(matches)}, duration_ms=_ms(start))


# ---------- listdir ----------
class ListdirArgs(BaseModel):
    path: str = Field(default=".", max_length=1024)
    max_entries: int = Field(default=500, ge=1, le=5000)


@router.post("/listdir", response_model=ToolResult, dependencies=[Depends(auth.verify_bearer)])
def tool_listdir(req: ListdirArgs) -> ToolResult:
    _require_enabled()
    start = time.time()
    p = _safe_relative_path(req.path)
    if not p.exists() or not p.is_dir():
        return ToolResult(ok=False, tool="listdir", error=f"not a directory: {req.path}", duration_ms=_ms(start))
    entries = []
    for child in sorted(p.iterdir()):
        try:
            entries.append({
                "name": child.name,
                "is_dir": child.is_dir(),
                "size": child.stat().st_size if child.is_file() else None,
            })
        except OSError:
            continue
        if len(entries) >= req.max_entries:
            break
    return ToolResult(ok=True, tool="listdir", result={"entries": entries, "count": len(entries)}, duration_ms=_ms(start))


# ---------- appstore (list installed skills on the server side) ----------
@router.get("/appstore", dependencies=[Depends(auth.verify_bearer)])
def tool_appstore() -> dict:
    _require_enabled()
    return {
        "ok": True,
        "tools": [
            {"name": "read",     "description": "Read a text file. Args: path, max_bytes.", "requires_confirm": False},
            {"name": "write",    "description": "Write a file. Args: path, content.",        "requires_confirm": True},
            {"name": "edit",     "description": "Find-and-replace in a file. Args: path, find, replace, expected_occurrences.", "requires_confirm": False},
            {"name": "shell",    "description": "Run a shell command. Args: command, cwd, timeout_seconds.", "requires_confirm": True},
            {"name": "grep",     "description": "Regex search across files. Args: pattern, path, max_matches.", "requires_confirm": False},
            {"name": "listdir",  "description": "List directory entries. Args: path, max_entries.", "requires_confirm": False},
        ],
        "confirm_token_ttl_seconds": _TOKEN_TTL_SECONDS,
    }


def _ms(start: float) -> int:
    return int((time.time() - start) * 1000)
