# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from constitutional_builder.v1 import builder_pb2 as constitutional__builder_dot_v1_dot_builder__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in constitutional_builder/v1/builder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuilderServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/constitutional_builder.v1.BuilderService/Health',
                request_serializer=constitutional__builder_dot_v1_dot_builder__pb2.HealthRequest.SerializeToString,
                response_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/constitutional_builder.v1.BuilderService/Execute',
                request_serializer=constitutional__builder_dot_v1_dot_builder__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.Replay = channel.unary_unary(
                '/constitutional_builder.v1.BuilderService/Replay',
                request_serializer=constitutional__builder_dot_v1_dot_builder__pb2.ReplayRequest.SerializeToString,
                response_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.ReplayResponse.FromString,
                _registered_method=True)
        self.Audit = channel.unary_unary(
                '/constitutional_builder.v1.BuilderService/Audit',
                request_serializer=constitutional__builder_dot_v1_dot_builder__pb2.AuditRequest.SerializeToString,
                response_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.AuditResponse.FromString,
                _registered_method=True)


class BuilderServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Audit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuilderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.HealthRequest.FromString,
                    response_serializer=constitutional__builder_dot_v1_dot_builder__pb2.HealthResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.ExecuteRequest.FromString,
                    response_serializer=constitutional__builder_dot_v1_dot_builder__pb2.DecisionResponse.SerializeToString,
            ),
            'Replay': grpc.unary_unary_rpc_method_handler(
                    servicer.Replay,
                    request_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.ReplayRequest.FromString,
                    response_serializer=constitutional__builder_dot_v1_dot_builder__pb2.ReplayResponse.SerializeToString,
            ),
            'Audit': grpc.unary_unary_rpc_method_handler(
                    servicer.Audit,
                    request_deserializer=constitutional__builder_dot_v1_dot_builder__pb2.AuditRequest.FromString,
                    response_serializer=constitutional__builder_dot_v1_dot_builder__pb2.AuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'constitutional_builder.v1.BuilderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('constitutional_builder.v1.BuilderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuilderService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constitutional_builder.v1.BuilderService/Health',
            constitutional__builder_dot_v1_dot_builder__pb2.HealthRequest.SerializeToString,
            constitutional__builder_dot_v1_dot_builder__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constitutional_builder.v1.BuilderService/Execute',
            constitutional__builder_dot_v1_dot_builder__pb2.ExecuteRequest.SerializeToString,
            constitutional__builder_dot_v1_dot_builder__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constitutional_builder.v1.BuilderService/Replay',
            constitutional__builder_dot_v1_dot_builder__pb2.ReplayRequest.SerializeToString,
            constitutional__builder_dot_v1_dot_builder__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Audit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/constitutional_builder.v1.BuilderService/Audit',
            constitutional__builder_dot_v1_dot_builder__pb2.AuditRequest.SerializeToString,
            constitutional__builder_dot_v1_dot_builder__pb2.AuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
